### ISSUE TITLE
Invalid operands to binary expression ('mtm::EventContainer::EventIterator *' and 'mtm::EventContainer::EventIterator')

### ISSUE THREAD

**Issue by Eladkay** [Adam11072000/MTM_EX3_TESTS#3]
test_partB.cpp:563:
ASSERT(++iter == ev1.end());

Sending this as an issue and not as a PR because I am not absolutely sure it's not a mistake on my part. Is it? I think ++iter should be a pointer.

**Comment by Adam11072000** [comment]
++iter should make the iterator point to the next element in the list, and end() returns an iterator. 
the segel specified that ++iter returns an iterator (we have operator* to get the element)
