### ISSUE TITLE
Conditional jump or move depends on uninitialised value(s)

### ISSUE THREAD

**Issue by Eladkay** [Adam11072000/MTM_EX3_TESTS#4]
In test_partB.cpp:84
        char c; //80
        output >> c;
        char ex;
        expOutput >> ex;
        if (ex != c) {
            return false;
        } // 86

The problem is in line 84 according to Valgrind.

**Comment by Adam11072000** [comment]
my valgrind doesn't show me leaks, tried it on my friend's code aswell with no leaks, i'll see to it and return back to you

**Comment by Adam11072000** [comment]
runned the tests on the ssh of the faculty, all is good, no leaks, check your file paths!!!!!!

**Comment by Eladkay** [comment]
I will check it, but clarifying - this is not a leak, this is a memory issue of the same sort as illegal access, segfaults, null deference.

**Comment by Eladkay** [comment]
Yes, you are correct, the problem was on my end and I apolgoise.

**Comment by Adam11072000** [comment]
No worries, i'm actually thankful you're helping XD
