### ISSUE TITLE
Function not necessarily defined  

### ISSUE THREAD

**Issue by Eladkay** [Adam11072000/MTM_EX3_TESTS#6]
schedule_tests.cpp:124:19: error: 'class mtm::BaseEvent' has no member named 'getName'
         if (event.getName() == "YanA") return false;

I don't think the segel requires this function, am I wrong?

**Comment by Adam11072000** [comment]
you are very true, the tests yan added are code-specific, i'll add a note stating that
i really don't have the time to work it.
if u can it would be really appreciated  mate 
cheers

**Comment by Eladkay** [comment]
This can't really be fixed, this exact test would just have to be removed or changed. I can't really change it myself either, but a note would be good

**Comment by Eladkay** [comment]
Ditto:
    DateWrap date2;
date_wrap_tests.cpp:111
This constructor does not, and should not, exist.

**Comment by Adam11072000** [comment]
Yes I told Yan. 
I'm aware the test has a lot of inaccuracies :/
Added a note about it though

**Comment by Eladkay** [comment]
Thank you very much and anyway for your work on this. It is very much appreciated.

**Comment by Adam11072000** [comment]
sorted it out, cheers mate.
